#!/bin/bash

data=$(date +'%d-%m-%Y')
hora=$(date "+%r" )

curl -s -X POST https://api.telegram.org/bot<bot_id>/sendMessage -d chat_id=<chat_id> -d text="Your PC has been powered on day $data at $hora logged in as $USER"

while [ -z $pass ]
do	
pass=$(zenity --password --width=250)
done
	
pass1=$(cat /usr/bin/pass.txt)
	
if [ $pass == $pass1 ]
then
	zenity --info --width=150 --timeout=3 --title=":)" --text="Wellcome"
        curl -s -X POST https://api.telegram.org/bot<bot_id>/sendMessage -d chat_id=<chat_id> -d text="Wellcome $USER"
else
	curl -s -X POST https://api.telegram.org/bot<bot_id>/sendMessage -d chat_id=<chat_id> -d text="User access attempt $USER"
	zenity --error --timeout=5 --width=450 --text="****** Worong password, a alert has been sended to the owner ******"
        systemctl poweroff -i
fi 

# Hugo Ferreira - 15/08/2021
