#!/bin/bash

bot=$(zenity --entry --width=250 --title="Atenção" --text="Digite o token do bot")
chat=$(zenity --entry --width=250 --title="Atenção" --text="Digite o id do chat")
msg=$(zenity --entry --width=250 --title="Atenção" --text="Digite a menssagem que deseja enviar")

curl -s -X POST https://api.telegram.org/bot$bot/sendMessage -d chat_id=$chat -d text="$msg"
